/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CampeonatosRouteImport } from './routes/campeonatos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipesIndexRouteImport } from './routes/equipes.index'
import { Route as EquipesIdRouteImport } from './routes/equipes_.$id'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosRoute = CampeonatosRouteImport.update({
  id: '/campeonatos',
  path: '/campeonatos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesIndexRoute = EquipesIndexRouteImport.update({
  id: '/equipes/',
  path: '/equipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesIdRoute = EquipesIdRouteImport.update({
  id: '/equipes_/$id',
  path: '/equipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campeonatos': typeof CampeonatosRoute
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/equipes/$id': typeof EquipesIdRoute
  '/equipes/': typeof EquipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campeonatos': typeof CampeonatosRoute
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/equipes/$id': typeof EquipesIdRoute
  '/equipes': typeof EquipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campeonatos': typeof CampeonatosRoute
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/equipes_/$id': typeof EquipesIdRoute
  '/equipes/': typeof EquipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campeonatos'
    | '/dashboard'
    | '/ranking'
    | '/equipes/$id'
    | '/equipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campeonatos'
    | '/dashboard'
    | '/ranking'
    | '/equipes/$id'
    | '/equipes'
  id:
    | '__root__'
    | '/'
    | '/campeonatos'
    | '/dashboard'
    | '/ranking'
    | '/equipes_/$id'
    | '/equipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampeonatosRoute: typeof CampeonatosRoute
  DashboardRoute: typeof DashboardRoute
  RankingRoute: typeof RankingRoute
  EquipesIdRoute: typeof EquipesIdRoute
  EquipesIndexRoute: typeof EquipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos': {
      id: '/campeonatos'
      path: '/campeonatos'
      fullPath: '/campeonatos'
      preLoaderRoute: typeof CampeonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes/': {
      id: '/equipes/'
      path: '/equipes'
      fullPath: '/equipes/'
      preLoaderRoute: typeof EquipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes_/$id': {
      id: '/equipes_/$id'
      path: '/equipes/$id'
      fullPath: '/equipes/$id'
      preLoaderRoute: typeof EquipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampeonatosRoute: CampeonatosRoute,
  DashboardRoute: DashboardRoute,
  RankingRoute: RankingRoute,
  EquipesIdRoute: EquipesIdRoute,
  EquipesIndexRoute: EquipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
